apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-kubernetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-kubernetes-app
  template:
    metadata:
      labels:
        app: flask-kubernetes-app
    spec:
      containers:
      - name: flask-kubernetes-app
        image: docker.io/aryachakraborty/flask-over-kubernetes:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_RUN_HOST
          valueFrom:
            secretKeyRef:
              name: flask-kubernetes-secret
              key: flask-run-host
        - name: FLASK_RUN_PORT
          valueFrom:
            secretKeyRef:
              name: flask-kubernetes-secret
              key: flask-run-port
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: flask-kubernetes-configmap
              key: flask-app-name
